import layoutParams_groups_density from './layoutParams_groups_density';
import layoutParams_groups_groupByOrientation from './layoutParams_groups_groupByOrientation';
import layoutParams_groups_numberOfGroupsPerRow from './layoutParams_groups_numberOfGroupsPerRow';
import layoutParams_groups_allowedGroupTypes from './layoutParams_groups_allowedGroupTypes';
import layoutParams_groups_repeatingGroupTypes from './layoutParams_groups_repeatingGroupTypes';
import layoutParams_groups_groupSize from './layoutParams_groups_groupSize';
import layoutParams_structure_galleryRatio_value from './layoutParams_structure_galleryRatio_value';
import layoutParams_structure_galleryRatio_includeExternalInfo from './layoutParams_structure_galleryRatio_includeExternalInfo';
import layoutParams_structure_galleryLayout from './layoutParams_structure_galleryLayout';
import layoutParams_structure_enableStreching from './layoutParams_structure_enableStreching';
import layoutParams_structure_gallerySpacing from './layoutParams_structure_gallerySpacing';
import layoutParams_structure_itemSpacing from './layoutParams_structure_itemSpacing';
import layoutParams_structure_scrollDirection from './layoutParams_structure_scrollDirection';
import layoutParams_structure_numberOfColumns from './layoutParams_structure_numberOfColumns';
import layoutParams_structure_numberOfGridRows from './layoutParams_structure_numberOfGridRows'; //NEW STYPEPARAMS METHOD need to import it from the new file... an old import was already here and might break.
import layoutParams_structure_responsiveMode from './layoutParams_structure_responsiveMode';
import layoutParams_structure_columnRatios from './layoutParams_structure_columnRatios';
import layoutParams_structure_scatter_randomScatter from './layoutParams_structure_scatter_randomScatter';
import layoutParams_structure_scatter_manualScatter from './layoutParams_structure_scatter_manualScatter';
import layoutParams_structure_layoutOrientation from './layoutParams_structure_layoutOrientation';
import layoutParams_structure_groupsOrder from './layoutParams_structure_groupsOrder';
import layoutParams_thumbnails_spacing from './layoutParams_thumbnails_spacing';
import layoutParams_thumbnails_size from './layoutParams_thumbnails_size';
import layoutParams_thumbnails_enable from './layoutParams_thumbnails_enable';
import layoutParams_thumbnails_position from './layoutParams_thumbnails_position';
import layoutParams_thumbnails_alignment from './layoutParams_thumbnails_alignment';

import layoutParams_navigationArrows_enable from './layoutParams_navigationArrows_enable';
import layoutParams_navigationArrows_size from './layoutParams_navigationArrows_size';
import layoutParams_navigationArrows_padding from './layoutParams_navigationArrows_padding';
import layoutParams_navigationArrows_position from './layoutParams_navigationArrows_position';
import layoutParams_navigationArrows_verticalAlignment from './layoutParams_navigationArrows_verticalAlignment';

import layoutParams_info_sizeUnits from './layoutParams_info_sizeUnits';
import layoutParams_info_width from './layoutParams_info_width';
import layoutParams_info_height from './layoutParams_info_height';
import layoutParams_info_spacing from './layoutParams_info_spacing';
import layoutParams_info_layout from './layoutParams_info_layout';
import layoutParams_info_border_width from './layoutParams_info_border_width';
import layoutParams_info_border_color from './layoutParams_info_border_color';
import layoutParams_info_border_radius from './layoutParams_info_border_radius';
import layoutParams_info_placement from './layoutParams_info_placement';

import layoutParams_targetItemSize_unit from './layoutParams_targetItemSize_unit';
import layoutParams_targetItemSize_value from './layoutParams_targetItemSize_value';
import layoutParams_targetItemSize_minimum from './layoutParams_targetItemSize_minimum';

import behaviourParams_item_clickAction from './behaviourParams_item_clickAction';
import behaviourParams_item_video_speed from './behaviourParams_item_video_speed';
import behaviourParams_item_video_volume from './behaviourParams_item_video_volume';
import behaviourParams_item_video_loop from './behaviourParams_item_video_loop';
import behaviourParams_item_video_playTrigger from './behaviourParams_item_video_playTrigger';
import behaviourParams_item_video_enablePlayButton from './behaviourParams_item_video_enablePlayButton';
import behaviourParams_item_video_enableControls from './behaviourParams_item_video_enableControls';
import behaviourParams_item_video_enablePlaceholder from './behaviourParams_item_video_enablePlaceholder';
import behaviourParams_item_overlay_hoveringBehaviour from './behaviourParams_item_overlay_hoveringBehaviour';
import behaviourParams_item_overlay_hoverAnimation from './behaviourParams_item_overlay_hoverAnimation';
import behaviourParams_item_overlay_position from './behaviourParams_item_overlay_position';
import behaviourParams_item_overlay_size from './behaviourParams_item_overlay_size';
import behaviourParams_item_overlay_sizeUnits from './behaviourParams_item_overlay_sizeUnits';
import behaviourParams_item_overlay_padding from './behaviourParams_item_overlay_padding';
import behaviourParams_item_overlay_backgroundColor from './behaviourParams_item_overlay_backgroundColor';
import behaviourParams_item_content_hoverAnimation from './behaviourParams_item_content_hoverAnimation';
import behaviourParams_item_content_placementAnimation from './behaviourParams_item_content_placementAnimation';
import behaviourParams_item_content_loader from './behaviourParams_item_content_loader';
import behaviourParams_item_content_magnificationValue from './behaviourParams_item_content_magnificationValue';
import behaviourParams_item_secondaryMedia_trigger from './behaviourParams_item_secondaryMedia_trigger';
import behaviourParams_item_secondaryMedia_behaviour from './behaviourParams_item_secondaryMedia_behaviour';

import behaviourParams_gallery_layoutDirection from './behaviourParams_gallery_layoutDirection';
import behaviourParams_gallery_blockContextMenu from './behaviourParams_gallery_blockContextMenu';
import behaviourParams_gallery_scrollAnimation from './behaviourParams_gallery_scrollAnimation';
import behaviourParams_gallery_enableIndexingShareLinks from './behaviourParams_gallery_enableIndexingShareLinks';
import behaviourParams_gallery_vertical_loadMore_enable from './behaviourParams_gallery_vertical_loadMore_enable';
import behaviourParams_gallery_vertical_loadMore_amount from './behaviourParams_gallery_vertical_loadMore_amount';
import behaviourParams_gallery_vertical_loadMore_text from './behaviourParams_gallery_vertical_loadMore_text';

import behaviourParams_gallery_horizontal_enableScrollSnap from './behaviourParams_gallery_horizontal_enableScrollSnap';
import behaviourParams_gallery_horizontal_slideAnimation from './behaviourParams_gallery_horizontal_slideAnimation';
import behaviourParams_gallery_horizontal_slideTransition from './behaviourParams_gallery_horizontal_slideTransition';
import behaviourParams_gallery_horizontal_blockScroll from './behaviourParams_gallery_horizontal_blockScroll';
import behaviourParams_gallery_horizontal_navigationDuration from './behaviourParams_gallery_horizontal_navigationDuration';
import behaviourParams_gallery_horizontal_loop from './behaviourParams_gallery_horizontal_loop';
import behaviourParams_gallery_horizontal_autoSlide_behaviour from './behaviourParams_gallery_horizontal_autoSlide_behaviour';
import behaviourParams_gallery_horizontal_autoSlide_interval from './behaviourParams_gallery_horizontal_autoSlide_interval';
import behaviourParams_gallery_horizontal_autoSlide_pauseOnHover from './behaviourParams_gallery_horizontal_autoSlide_pauseOnHover';
import behaviourParams_gallery_horizontal_autoSlide_speed from './behaviourParams_gallery_horizontal_autoSlide_speed';
import behaviourParams_gallery_horizontal_slideshowInfo_buttonsAlignment from './behaviourParams_gallery_horizontal_slideshowInfo_buttonsAlignment';
import behaviourParams_gallery_horizontal_slideshowInfo_enableCounter from './behaviourParams_gallery_horizontal_slideshowInfo_enableCounter';
import behaviourParams_gallery_horizontal_slideshowInfo_enablePlayButton from './behaviourParams_gallery_horizontal_slideshowInfo_enablePlayButton';

import stylingParams_arrowsColor from './stylingParams_arrowsColor';
import stylingParams_itemShadowBlur from './stylingParams_itemShadowBlur';
import stylingParams_itemShadowDirection from './stylingParams_itemShadowDirection';
import stylingParams_itemShadowOpacityAndColor from './stylingParams_itemShadowOpacityAndColor';
import stylingParams_itemShadowSize from './stylingParams_itemShadowSize';
import stylingParams_itemEnableShadow from './stylingParams_itemEnableShadow';
import stylingParams_itemBorderRadius from './stylingParams_itemBorderRadius';
import stylingParams_itemBorderWidth from './stylingParams_itemBorderWidth';
import stylingParams_itemBorderColor from './stylingParams_itemBorderColor';
import stylingParams_itemResolutionMode from './stylingParams_itemResolutionMode';
import layoutParams_crop_ratios from './layoutParams_crop_ratios';
import layoutParams_crop_enable from './layoutParams_crop_enable';
import layoutParams_crop_method from './layoutParams_crop_method';
import layoutParams_crop_alignment from './layoutParams_crop_alignment';
import layoutParams_crop_cropOnlyFill from './layoutParams_crop_cropOnlyFill';
import layoutParams_crop_enableSmartCrop from './layoutParams_crop_enableSmartCrop';

import layoutParams_navigationArrows_type from './layoutParams_navigationArrows_type';
import layoutParams_navigationArrows_container_type from './layoutParams_navigationArrows_container_type';
import layoutParams_navigationArrows_container_backgroundColor from './layoutParams_navigationArrows_container_backgroundColor';
import layoutParams_navigationArrows_container_borderRadius from './layoutParams_navigationArrows_container_borderRadius';
import layoutParams_navigationArrows_mouseCursorContainerMaxWidth from './layoutParams_navigationArrows_mouseCursorContainerMaxWidth';
//Layouter direct
import fixedColumns from './fixedColumns';
//Layouter direct

export default {
  layoutParams_groups_density,
  layoutParams_groups_groupByOrientation,
  layoutParams_groups_numberOfGroupsPerRow,
  layoutParams_groups_allowedGroupTypes,
  layoutParams_groups_repeatingGroupTypes,
  layoutParams_groups_groupSize,

  layoutParams_structure_galleryRatio_value,
  layoutParams_structure_galleryRatio_includeExternalInfo,
  layoutParams_structure_galleryLayout,
  layoutParams_structure_enableStreching,
  layoutParams_structure_gallerySpacing,
  layoutParams_structure_itemSpacing,
  layoutParams_structure_scrollDirection,
  layoutParams_structure_numberOfColumns,
  layoutParams_structure_numberOfGridRows,
  layoutParams_structure_responsiveMode,
  layoutParams_structure_columnRatios,
  layoutParams_structure_scatter_randomScatter,
  layoutParams_structure_scatter_manualScatter,
  layoutParams_structure_layoutOrientation,
  layoutParams_structure_groupsOrder,

  layoutParams_thumbnails_spacing,
  layoutParams_thumbnails_size,
  layoutParams_thumbnails_enable,
  layoutParams_thumbnails_position,
  layoutParams_thumbnails_alignment,

  layoutParams_navigationArrows_enable,
  layoutParams_navigationArrows_size,
  layoutParams_navigationArrows_padding,
  layoutParams_navigationArrows_position,
  layoutParams_navigationArrows_verticalAlignment,
  layoutParams_navigationArrows_type,
  layoutParams_navigationArrows_container_type,
  layoutParams_navigationArrows_container_borderRadius,
  layoutParams_navigationArrows_container_backgroundColor,
  layoutParams_navigationArrows_mouseCursorContainerMaxWidth,

  layoutParams_info_sizeUnits,
  layoutParams_info_width,
  layoutParams_info_height,
  layoutParams_info_spacing,
  layoutParams_info_layout,
  layoutParams_info_border_width,
  layoutParams_info_border_color,
  layoutParams_info_border_radius,
  layoutParams_info_placement,

  layoutParams_targetItemSize_unit,
  layoutParams_targetItemSize_value,
  layoutParams_targetItemSize_minimum,

  behaviourParams_item_clickAction,
  behaviourParams_item_video_speed,
  behaviourParams_item_video_volume,
  behaviourParams_item_video_loop,
  behaviourParams_item_video_playTrigger,
  behaviourParams_item_video_enablePlayButton,
  behaviourParams_item_video_enableControls,
  behaviourParams_item_video_enablePlaceholder,
  behaviourParams_item_overlay_hoveringBehaviour,
  behaviourParams_item_overlay_hoverAnimation,
  behaviourParams_item_overlay_position,
  behaviourParams_item_overlay_size,
  behaviourParams_item_overlay_sizeUnits,
  behaviourParams_item_overlay_padding,
  behaviourParams_item_overlay_backgroundColor,
  behaviourParams_item_content_hoverAnimation,
  behaviourParams_item_content_placementAnimation,
  behaviourParams_item_content_loader,
  behaviourParams_item_content_magnificationValue,
  behaviourParams_item_secondaryMedia_trigger,
  behaviourParams_item_secondaryMedia_behaviour,
  behaviourParams_gallery_layoutDirection,
  behaviourParams_gallery_blockContextMenu,
  behaviourParams_gallery_scrollAnimation,
  behaviourParams_gallery_enableIndexingShareLinks,
  behaviourParams_gallery_vertical_loadMore_enable,
  behaviourParams_gallery_vertical_loadMore_amount,
  behaviourParams_gallery_vertical_loadMore_text,

  behaviourParams_gallery_horizontal_enableScrollSnap,
  behaviourParams_gallery_horizontal_slideAnimation,
  behaviourParams_gallery_horizontal_slideTransition,
  behaviourParams_gallery_horizontal_blockScroll,
  behaviourParams_gallery_horizontal_navigationDuration,
  behaviourParams_gallery_horizontal_loop,
  behaviourParams_gallery_horizontal_autoSlide_behaviour,
  behaviourParams_gallery_horizontal_autoSlide_interval,
  behaviourParams_gallery_horizontal_autoSlide_pauseOnHover,
  behaviourParams_gallery_horizontal_autoSlide_speed,
  behaviourParams_gallery_horizontal_slideshowInfo_buttonsAlignment,
  behaviourParams_gallery_horizontal_slideshowInfo_enableCounter,
  behaviourParams_gallery_horizontal_slideshowInfo_enablePlayButton,

  stylingParams_arrowsColor,
  stylingParams_itemShadowBlur,
  stylingParams_itemShadowDirection,
  stylingParams_itemShadowOpacityAndColor,
  stylingParams_itemShadowSize,
  stylingParams_itemEnableShadow,
  stylingParams_itemBorderRadius,
  stylingParams_itemBorderColor,
  stylingParams_itemBorderWidth,
  stylingParams_itemResolutionMode,

  layoutParams_crop_enable,
  layoutParams_crop_method,
  layoutParams_crop_alignment,
  layoutParams_crop_cropOnlyFill,
  layoutParams_crop_enableSmartCrop,
  layoutParams_crop_ratios,

  //Layouter direct
  fixedColumns,
  //Layouter direct
};
// TODO = add the options:
/*
itemOpacity
imageLoadingColor
oneColorAnimationColor
*/
