compressionLevel: 0

enableGlobalCache: true

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0007
    level: discard
  - code: YN0013
    level: discard
  - code: YN0032
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"


yarnPath: .yarn/releases/yarn-3.2.1.cjs
