const SCROLL_ANIMATIONS = {
  FADE: 'FADE',
  ZOOM: 'ZOOM',
  GRAYSCALE: 'GRAYSCALE',
  SIZE: 'SIZE',
  SHADOW: 'SHADOW',
  BLUR: 'BLUR',
  ROUND: 'ROUND',
  ONE_COLOR: 'ONE_COLOR',
  MAIN_COLOR: 'MAIN_COLOR',
  ROTATE: 'ROTATE',
  SPIRAL: 'SPIRAL',
  SQUEEZE: 'SQUEEZE',
  FLIP: 'FLIP',
  SLIDE: 'SLIDE',
  APPEAR: 'APPEAR',
  PAN: 'PAN',
  SKEW: 'SKEW',
};

export default SCROLL_ANIMATIONS;
