const SCROLL_ANIMATIONS = {
  NO_EFFECT: 'NO_EFFECT',
  FADE_IN: 'FADE_IN',
  GRAYSCALE: 'GRAYSCALE',
  SLIDE_UP: 'SLIDE_UP',
  SLIDE_IN: 'SLIDE_IN',
  SLIDE_IN_REVERSED: 'SLIDE_IN_REVERSED',
  EXPAND: 'EXPAND',
  SQUEEZE: 'SQUEEZE',
  FLIP: 'FLIP',
  ROTATE: 'ROTATE',
  ZOOM_IN: 'ZOOM_IN',
  ZOOM_OUT: 'ZOOM_OUT',
  ONE_COLOR: 'ONE_COLOR',
  MAIN_COLOR: 'MAIN_COLOR',
  BLUR: 'BLUR',
  HINGE: 'HINGE',
};

export default SCROLL_ANIMATIONS;
