export const SECTIONS = {
    PRESET: 'Presets',
    LAYOUT: 'Layout Customization',
    ADVANCED: 'Advanced Layout Settings',
    BEHAVIOR: 'Behavior Settings',
    INFO: 'Item info',
    DESIGN: 'Design Settings',
    ANIMATION: 'Animations',
    IMAGE: 'Image',
    VIDEO: 'Videos',
};

export const SECTIONS_ORDER = {
    PRESET: 1,
    LAYOUT: 2,
    ADVANCED: 3,
    BEHAVIOR: 4,
    INFO: 5,
    DESIGN: 6,
    ANIMATION: 7,
    IMAGE: 8,
    VIDEO: 9,
    STORE: 10,
};

export const stylesBySection = {
    [SECTIONS.PRESET]: [
        'galleryLayout',//: always,
    ],
    [SECTIONS.LAYOUT]: [
        'scrollDirection',//: sp => [GALLERY_CONSTS.layout.EMPTY, GALLERY_CONSTS.layout.COLLAGE, GALLERY_CONSTS.layout.GRID].indexOf(sp.galleryLayout) > -1,
        'isVertical',//: sp => [GALLERY_CONSTS.layout.COLLAGE, GALLERY_CONSTS.layout.MASONRY].indexOf(sp.galleryLayout) > -1,
        'isRTL',//: sp => [GALLERY_CONSTS.layout.PANORAMA].indexOf(sp.galleryLayout) === -1,
        'imageMargin',//: sp => [GALLERY_CONSTS.layout.EMPTY, GALLERY_CONSTS.layout.COLLAGE, GALLERY_CONSTS.layout.MASONRY, GALLERY_CONSTS.layout.GRID, GALLERY_CONSTS.layout.SLIDER, GALLERY_CONSTS.layout.PANORAMA, GALLERY_CONSTS.layout.COLUMN, GALLERY_CONSTS.layout.BRICKS, GALLERY_CONSTS.layout.MIX, GALLERY_CONSTS.layout.ALTERNATE].indexOf(sp.galleryLayout) > -1,

        'gridStyle',//: sp => ((sp.galleryLayout === GALLERY_CONSTS.layout.GRID || sp.galleryLayout === GALLERY_CONSTS.layout.COLLAGE) && !oneRow(sp)),
        'numberOfImagesPerRow',//: sp => ((sp.galleryLayout === GALLERY_CONSTS.layout.GRID || sp.galleryLayout === GALLERY_CONSTS.layout.COLLAGE) && !oneRow(sp)) && sp.gridStyle === 1,
        'numberOfImagesPerCol',//: sp => [GALLERY_CONSTS.layout.GRID].indexOf(sp.galleryLayout) >= 0  && (sp.galleryLayout === GALLERY_CONSTS.layout.COLLAGE && !oneRow(sp)),

        'collageDensity',//: sp => [GALLERY_CONSTS.layout.EMPTY, GALLERY_CONSTS.layout.COLLAGE].indexOf(sp.galleryLayout) >= 0,

        'cubeImages',//: showThumbnailResize,
        'cubeType',//: showThumbnailResize,
        'cubeRatio',//: sp => [GALLERY_CONSTS.layout.EMPTY, GALLERY_CONSTS.layout.GRID, GALLERY_CONSTS.layout.SLIDER].indexOf(sp.galleryLayout) > -1 && sp.cubeType === GALLERY_CONSTS.cubeType.crop,
        'gallerySliderImageRatio',//: sp => sp.galleryLayout === GALLERY_CONSTS.layout.SLIDER && sp.cubeType === GALLERY_CONSTS.cubeType.crop,

        'slideshowLoop',//: showSlideshowSettings,
        'isAutoSlideshow',//: showAutoSlideshow,
        'autoSlideshowInterval',//: (sp) => showAutoSlideshow(sp) && sp.isAutoSlideshow,
        'slideshowInfoSize',//: isSlideshowLayout,
        'playButtonForAutoSlideShow',//: isSlideshowLayout,

        'galleryThumbnailsAlignment',//: sp => [GALLERY_CONSTS.layout.THUMBNAIL].indexOf(sp.galleryLayout) >= 0,
        'thumbnailSize',//: sp => [GALLERY_CONSTS.layout.THUMBNAIL].indexOf(sp.galleryLayout) >= 0,
        'thumbnailSpacings',//: sp => [GALLERY_CONSTS.layout.EMPTY, GALLERY_CONSTS.layout.THUMBNAIL].indexOf(sp.galleryLayout) > -1,

        'magicLayoutSeed',//: sp => [GALLERY_CONSTS.layout.MAGIC].indexOf(sp.galleryLayout) > -1,
    ],
    [SECTIONS.ADVANCED]: [
        'gallerySizeType',//: showGallerySize,
        'gallerySize',//: sp => showGallerySize(sp) && [GALLERY_CONSTS.gallerySizeType.PIXELS, GALLERY_CONSTS.gallerySizeType.RATIO].indexOf(sp.gallerySizeType) < 0,
        'gallerySizePx',//: sp => showGallerySize(sp) && GALLERY_CONSTS.gallerySizeType.PIXELS === sp.gallerySizeType,
        'gallerySizeRatio',//: sp => showGallerySize(sp) && GALLERY_CONSTS.gallerySizeType.RATIO === sp.gallerySizeType,
        'groupSize',//: sp => sp.galleryLayout === GALLERY_CONSTS.layout.COLLAGE,
        'groupTypes',//: sp => sp.galleryLayout === GALLERY_CONSTS.layout.COLLAGE,
        'rotatingGroupTypes',//: sp => sp.galleryLayout === GALLERY_CONSTS.layout.COLLAGE,
        'groupsPerStrip',//: sp => sp.galleryLayout === GALLERY_CONSTS.layout.COLLAGE,
        'galleryMargin',//: always,
        'floatingImages',//: always,
    ],
    [SECTIONS.INFO]: [
        'titlePlacement',//: (sp) => layoutPresentOuterInformation(sp) && showTexts(sp),
        'itemOpacity',//: showColorOverlay,
        'allowTitle',//: showImagesDisplaySection,
        'allowDescription',//: showImagesDisplaySection,
        'allowSlideshowCounter',//: (sp) => isSlideshowLayout(sp) && sp.isAutoSlideshow,
        'allowDownload',//: always,
        'allowSocial',//: always,
        'loveButton',//: always,
        'loveCounter',//: (sp) => sp.loveButton,
        'useCustomButton',//: sp => showButtonSection(sp),
    ],
    [SECTIONS.BEHAVIOR]: [
        'enableInfiniteScroll',//: sp => [GALLERY_CONSTS.layout.COLLAGE,  GALLERY_CONSTS.layout.MASONRY,  GALLERY_CONSTS.layout.GRID,  GALLERY_CONSTS.layout.PANORAMA].indexOf(sp.galleryLayout) > -1 && !oneRow(sp) ,
        'loadMoreAmount',//: sp => [GALLERY_CONSTS.layout.COLLAGE,  GALLERY_CONSTS.layout.MASONRY,  GALLERY_CONSTS.layout.GRID,  GALLERY_CONSTS.layout.PANORAMA].indexOf(sp.galleryLayout) > -1 && !oneRow(sp) && sp.enableInfiniteScroll, 
        'hoveringBehaviour',//: showHoveringBehaviour,
        'itemClick',//: sp => !isStore(sp),
        'scrollSnap',//: sp => isHorizontalLayout(sp),
    ],
    [SECTIONS.STORE]: [
        'isStore',//: always,
        'canUseWatermark',//: sp => isStore(sp),
        'useWatermark',//: sp => canUseWatermark(sp),
        'watermarkOpacity',//: sp => canUseWatermark(sp) && sp.useWatermark,
        'watermarkSize',//: sp => canUseWatermark(sp) && sp.useWatermark,
        'watermarkDock',//: sp => canUseWatermark(sp) && sp.useWatermark,
    ],
    [SECTIONS.DESIGN]: [
        'arrowsSize',//: isHorizontalLayout,
        'arrowsColor',//: isHorizontalLayout,
        'arrowsPosition',//: isHorizontalLayout, // && showOldGalleryFeaturesDesign,

        'itemIconColorSlideshow',//: isSlideshowLayout,
        'itemIconColor',//: sp => !isSlideshowLayout(sp),
        'itemFont',//: sp => showTextSubSection(sp) && (sp.allowTitle && !(isSlideshowLayout(sp) || presentOuterInformation(sp))),
        'itemFontColor',//: sp => showTextSubSection(sp) && (sp.allowTitle && !(isSlideshowLayout(sp) || presentOuterInformation(sp))),
        'itemFontSlideshow',//: sp => showTextSubSection(sp) && (sp.allowTitle && (isSlideshowLayout(sp) || presentOuterInformation(sp))),
        'itemFontColorSlideshow',//: sp => showTextSubSection(sp) && (sp.allowTitle && (isSlideshowLayout(sp) || presentOuterInformation(sp))),
        'itemDescriptionFont',//: sp => showTextSubSection(sp) && (sp.allowDescription && !(isSlideshowLayout(sp) || presentOuterInformation(sp))),
        'itemDescriptionFontColor',//: sp => showTextSubSection(sp) && (sp.allowDescription && !(isSlideshowLayout(sp) || presentOuterInformation(sp))),
        'itemDescriptionFontSlideshow',//: sp => showTextSubSection(sp) && (sp.allowDescription && (isSlideshowLayout(sp) || presentOuterInformation(sp))),
        'itemDescriptionFontColorSlideshow',//: sp => showTextSubSection(sp) && (sp.allowDescription && (isSlideshowLayout(sp) || presentOuterInformation(sp))),
        'galleryHorizontalAlign',//: sp => showTextSubSection(sp), // ALSO sets galleryTextAlign ---sp => showTextSubSection(sp),
        'galleryVerticalAlign',//: sp => showTextSubSection(sp) && showAlignTextVertical(sp),
        'textBoxFillColor',//: sp => showTextSubSection(sp) && (!isSlideshowLayout(sp) && presentOuterInformation(sp) && (sp.infoType === GALLERY_CONSTS.infoType.ATTACHED_BACKGROUND || sp.infoType === GALLERY_CONSTS.infoType.SEPARATED_BACKGROUND)) ,
        'calculateTextBoxHeightMode',//: sp => showTextSubSection(sp) && (!isSlideshowLayout(sp) && presentOuterInformation(sp)) ,
        'textBoxHeight',//: sp => showTextSubSection(sp) && (!isSlideshowLayout(sp) && presentOuterInformation(sp) && sp.calculateTextBoxHeightMode === GALLERY_CONSTS.calculationOptions.MANUAL) ,
        'textImageSpace',//: sp =>  showTextSubSection(sp) && (!isSlideshowLayout(sp) && presentOuterInformation(sp) && sp.infoType === GALLERY_CONSTS.infoType.SEPARATED_BACKGROUND)  ,
        'textBoxBorderRadius',//: sp =>  showTextSubSection(sp) && (!isSlideshowLayout(sp) && presentOuterInformation(sp) && sp.infoType === GALLERY_CONSTS.infoType.SEPARATED_BACKGROUND)  ,
        'textBoxBorderWidth',//: sp =>  showTextSubSection(sp) && (!isSlideshowLayout(sp) && presentOuterInformation(sp) && sp.infoType === GALLERY_CONSTS.infoType.SEPARATED_BACKGROUND)  ,
        'textBoxBorderColor',//: sp =>  showTextSubSection(sp) && (!isSlideshowLayout(sp) && presentOuterInformation(sp) && sp.infoType === GALLERY_CONSTS.infoType.SEPARATED_BACKGROUND)  ,
        'textsVerticalPadding',//: sp =>  showTextSubSection(sp) && (!isSlideshowLayout(sp) && (sp.titlePlacement !== GALLERY_CONSTS.placements.SHOW_ON_HOVER || !sp.galleryVerticalAlign === 'center')),
        'textsHorizontalPadding',//: sp =>  showTextSubSection(sp) && (!isSlideshowLayout(sp)) ,
        'titleDescriptionSpace',//: sp =>  showTextSubSection(sp) && (!isSlideshowLayout(sp) && sp.allowTitle && sp.allowDescription),
        'customButtonText',//: sp => showButtonSection(sp) && sp.useCustomButton,
        'customButtonFontForHover',//: sp => showButtonSection(sp) && sp.useCustomButton && isTitlePlacementAlwaysShown(sp),
        'customButtonFontColorForHover',//: sp => showButtonSection(sp) && sp.useCustomButton && isTitlePlacementAlwaysShown(sp),
        'customButtonFont',//: sp =>showButtonSection(sp) &&  sp.useCustomButton && !isTitlePlacementAlwaysShown(sp),
        'customButtonFontColor',//: sp => showButtonSection(sp) && sp.useCustomButton && !isTitlePlacementAlwaysShown(sp),
        'customButtonColor',//: sp => showButtonSection(sp) && sp.useCustomButton && !isTitlePlacementAlwaysShown(sp),
        'customButtonBorderWidth',//: sp => showButtonSection(sp) && sp.useCustomButton && !isTitlePlacementAlwaysShown(sp),
        'customButtonBorderColor',//: sp => showButtonSection(sp) && sp.useCustomButton && !isTitlePlacementAlwaysShown(sp),
        'customButtonBorderRadius',//: sp => showButtonSection(sp) && sp.useCustomButton && !isTitlePlacementAlwaysShown(sp),
        'loadMoreButtonText',//: sp => showButtonSection(sp) && showInfiniteScroll(sp) && !sp.enableInfiniteScroll ,
        'loadMoreButtonFont',//: sp => showButtonSection(sp) && showInfiniteScroll(sp) && !sp.enableInfiniteScroll ,
        'loadMoreButtonFontColor',//: sp => showButtonSection(sp) && showInfiniteScroll(sp) && !sp.enableInfiniteScroll ,
        'loadMoreButtonColor',//: sp => showButtonSection(sp) && showInfiniteScroll(sp) && !sp.enableInfiniteScroll ,
        'loadMoreButtonBorderWidth',//: sp => showButtonSection(sp) && showInfiniteScroll(sp) && !sp.enableInfiniteScroll ,
        'loadMoreButtonBorderColor',//: sp => showButtonSection(sp) && showInfiniteScroll(sp) && !sp.enableInfiniteScroll , 
        'loadMoreButtonBorderRadius',//: sp => showButtonSection(sp) && showInfiniteScroll(sp) && !sp.enableInfiniteScroll ,
        'imageInfoType',//: sp => presentOuterInformation(sp) && showTexts(sp),
        'itemBorderWidth',//: showItemBorderAndShadowConfig,
        'itemBorderColor',//: showItemBorderAndShadowConfig,
        'itemBorderRadius',//: showItemBorderAndShadowConfig,
        'itemEnableShadow',//: showShadow,
        'itemShadowOpacityAndColor',//: sp => showShadow(sp) && sp.itemEnableShadow,
        'itemShadowBlur',//: sp => showShadow(sp) && sp.itemEnableShadow,
        'itemShadowDirection',//: sp => showShadow(sp) && sp.itemEnableShadow,
        'itemShadowSize',//: sp => showShadow(sp) && sp.itemEnableShadow,
    ],
    [SECTIONS.ANIMATION]: [
        'overlayAnimation',//:  sp => !isSlideshowLayout(sp) && !(sp.titlePlacement === GALLERY_CONSTS.placements.SHOW_ON_HOVER &&  sp.hoveringBehaviour === GALLERY_CONSTS.infoBehaviourOnHover.NO_CHANGE),
        'imageHoverAnimation',//: sp => !isSlideshowLayout(sp),
        'imageLoadingMode',//: always,
        'imageLoadingColor',//: sp => sp.imageLoadingMode === GALLERY_CONSTS.loadingMode.COLOR,
        'scrollAnimation',//: sp => showScrollAnimations(sp),
        'oneColorAnimationColor',//: sp => showScrollAnimations(sp) && sp.scrollAnimation === GALLERY_CONSTS.scrollAnimations.ONE_COLOR,
    ],
    [SECTIONS.IMAGE]: [
        'imageQuality',//: always,
        'usmToggle',//: always,
        'usm_a',//: sp => sp.usmToggle,
        'usm_r',//: sp => sp.usmToggle,
        'usm_t',//: sp => sp.usmToggle,
    ],
    [SECTIONS.VIDEO]: [
        'videoPlay',//: always,
        'videoSound',//: sp => sp.videoPlay !== GALLERY_CONSTS.videoPlay.ON_CLICK,
        'videoSpeed',//: always,
        'videoLoop',//: always
    ],
}

export const stylesList = [].concat(...Object.values(stylesBySection));
export const sectionByStyle = Object.assign({},
    ...Object.entries(stylesBySection).map(([section, styleParams]) => styleParams.reduce((obj, styleParam) => ({
        ...obj,
        [styleParam]: section
    }), {}))
);