import { expect } from 'chai';
import _ from 'lodash';
import defaultStyles from '../src/common/defaultStyles';
import { flattenObject } from '../src/core/helpers/stylesUtils';
import GALLERY_CONSTS from '../src/common/constants';

describe('defaultStyles', () => {
  it('should return the expected styles unchanged', () => {
    const actual = flattenObject(defaultStyles);
    const expected = flattenObject(expectedStyles());
    expect(_.isEqual(actual, expected)).eq(true);
    const actualLength = _.keys(actual).length;
    expect(actualLength).eq(_.keys(expected).length);
    expect(actualLength).eq(104);
  });
});

function expectedStyles() {
  return {
    layoutParams: {
      gallerySpacing: 0,
      cropRatio: 1,
      repeatingGroupTypes: '',
    },
    isRTL: false,
    isVertical: false,
    minItemSize: 120,
    groupSize: 3,
    chooseBestGroup: true,
    groupTypes: '1,2h,2v,3t,3b,3l,3r',
    cubeImages: false,
    cubeType: 'fill',
    smartCrop: false,
    fullscreen: true,
    videoLoop: true,
    videoSound: false,
    videoPlay: 'hover',
    videoSpeed: '1',
    numberOfImagesPerRow: 3,
    collageDensity: 0.8,
    galleryTextAlign: 'center',
    imageMargin: 10,
    fixedColumns: 0,
    showArrows: true,
    hasThumbnails: false,
    isSlideshow: false,
    galleryThumbnailsAlignment: 'bottom',
    gridStyle: 0,
    titlePlacement: 'SHOW_ON_HOVER',
    hoveringBehaviour: 'APPEARS',
    isAutoSlideshow: false,
    slideshowLoop: false,
    playButtonForAutoSlideShow: false,
    pauseAutoSlideshowOnHover: true,
    allowSlideshowCounter: false,
    autoSlideshowInterval: 4,
    arrowsSize: 23,
    slideshowInfoSize: 200,
    imageLoadingMode: 'BLUR',
    scrollAnimation: 'NO_EFFECT',
    overlayAnimation: 'NO_EFFECT',
    imageHoverAnimation: 'NO_EFFECT',
    itemBorderWidth: 0,
    itemBorderRadius: 0,
    itemEnableShadow: false,
    itemShadowBlur: 20,
    loadMoreAmount: 'all',
    itemShadowDirection: 135,
    itemShadowSize: 10,
    imageInfoType: 'NO_BACKGROUND',
    textBoxBorderRadius: 0,
    textBoxBorderWidth: 0,
    textBoxHeight: 200,
    textImageSpace: 10,
    scrollDirection: 0,
    slideAnimation: 'SCROLL',
    autoSlideshowType: 'interval',
    autoSlideshowContinuousSpeed: 200,
    gallerySizePx: 0,
    gallerySizeRatio: 0,
    gallerySizeType: 'smart',
    itemShadowOpacityAndColor: '',
    arrowsColor: '',
    textBoxBorderColor: '',
    allowContextMenu: false,
    hidePlay: false,
    gallerySize: 30,
    cropOnlyFill: false,
    rotatingCropRatios: '',
    columnWidths: '',
    numberOfImagesPerCol: 1,
    groupsPerStrip: 0,
    scatter: 0,
    rotatingScatter: '',
    placeGroupsLtr: false,
    enableInfiniteScroll: true,
    thumbnailSpacings: 4,
    enableScroll: true,
    isGrid: false,
    isSlider: false,
    isColumns: false,
    isMasonry: false,
    scrollSnap: false,
    itemClick: 'nothing',
    scrollDuration: 400,
    arrowsPosition: 0,
    arrowsVerticalPosition: 'ITEM_CENTER',
    arrowsPadding: 23,
    thumbnailSize: 120,
    magicLayoutSeed: 1,
    imagePlacementAnimation: 'NO_EFFECT',
    calculateTextBoxWidthMode: 'PERCENT',
    textBoxWidth: 200,
    textBoxWidthPercent: 50,
    loadMoreButtonText: '',
    showVideoControls: false,
    shouldIndexDirectShareLinkInSEO: true,
    slideTransition: 'cubic-bezier(0.46,0.1,0.25,1)',
    useMaxDimensions: false,
    enableVideoPlaceholder: true,
    overlayPosition: 'LEFT',
    overlaySize: 100,
    overlaySizeType: 'PERCENT',
    overlayPadding: 0,
    cubeFitPosition: GALLERY_CONSTS.cubeFitPosition.MIDDLE,
  };
}
