export const SET_ITEMS = 'SET_ITEMS';
export const SET_RENDERED_ITEMS_COUNT = 'SET_RENDERED_ITEMS_COUNT';

export const GALLERY_WINDOW_LAYOUT_CHANGED = 'GALLERY_WINDOW_LAYOUT_CHANGED';
export const VIDEO_ENDED = 'VIDEO_ENDED';
export const VIDEO_ADDED = 'VIDEO_ADDED';
export const VIDEO_REMOVED = 'VIDEO_REMOVED';
export const NAVIGATION_IN = 'NAVIGATION_IN';
export const EDITOR_MODE_CHANGED = 'EDITOR_MODE_CHANGED';
export const TOGGLE_ISINVIEW = 'TOGGLE_ISINVIEW';
export const SET_VIDEO_PLAY_INDEX = 'SET_VIDEO_PLAY_INDEX';
export const VIDEO_MODE_CHANGED = 'VIDEO_MODE_CHANGED';
