#!/usr/bin/env bash
previous_tag=0

printf "<!-- THIS FILE IS AUTOGENERATED! DO NOT TRY TO CHANGE IT MANUALLY -->\n"
printf "<!-- see: scripts/changelog-builder.sh -->\n\n"

for current_tag in $(git tag --list 'v4*' --sort=-v:refname)
do

if [ "$previous_tag" != 0 ];then
    tag_date=$(git log -1 --pretty=format:'%ad' --date=short ${previous_tag})
    printf "## [${previous_tag}](https://github.com/wix/pro-gallery/compare/${current_tag}...${previous_tag}) (${tag_date})\n\n"
    git log ${current_tag}...${previous_tag} --pretty=format:'*  %s [%h](https://github.com/wix/pro-gallery/commit/%H)' --reverse | grep -v -e Merge -e "v4." -e "v3.1" | sed -E "s/(\()(\#)([0-9]*)(\))/([\2\3](https:\/\/github.com\/wix\/pro-gallery\/pull\/\3))/"
    printf "\n\n"
fi
previous_tag=${current_tag}
done
