const EVENTS = {
  ITEM_CREATED: 'ITEM_CREATED',
  ITEM_LOADED: 'ITEM_LOADED',
  GALLERY_CHANGE: 'GALLERY_CHANGE',
  ITEM_ACTION_TRIGGERED: 'ITEM_ACTION_TRIGGERED',
  CURRENT_ITEM_CHANGED: 'CURRENT_ITEM_CHANGED',
  SHARE_BUTTON_CLICKED: 'SHARE_BUTTON_CLICKED',
  NEED_MORE_ITEMS: 'NEED_MORE_ITEMS',
  //itemActions
  PREVIEW_SHARE_BUTTON_MOUSE_OVER: 'PREVIEW_SHARE_BUTTON_MOUSE_OVER',
  PREVIEW_SHARE_BUTTON_MOUSE_OUT: 'PREVIEW_SHARE_BUTTON_MOUSE_OUT',
  DEMO_DOWNLOAD_BUTTON_MOUSE_OVER: 'DEMO_DOWNLOAD_BUTTON_MOUSE_OVER',
  DEMO_DOWNLOAD_BUTTON_MOUSE_OUT: 'DEMO_DOWNLOAD_BUTTON_MOUSE_OUT',
  PREVIEW_LOVE_BUTTON_MOUSE_OVER: 'PREVIEW_LOVE_BUTTON_MOUSE_OVER',
  PREVIEW_LOVE_BUTTON_MOUSE_OUT: 'PREVIEW_LOVE_BUTTON_MOUSE_OUT',
  TEXT_DOWNLOAD_BUTTON_CLICKED: 'TEXT_DOWNLOAD_BUTTON_CLICKED',
  LOVE_BUTTON_CLICKED: 'LOVE_BUTTON_CLICKED',
  //bi Only
  ITEM_CLICKED: 'ITEM_CLICKED',
  DOWNLOAD_BUTTON_CLICKED: 'DOWNLOAD_BUTTON_CLICKED',
  BUY_NOW_CLICKED: 'BUY_NOW_CLICKED',
  THUMBNAIL_CLICKED: 'THUMBNAIL_CLICKED',
};

export default EVENTS;
