const EVENTS = {
  ITEM_CREATED: 'ON_ITEM_CREATED',
  ITEM_LOADED: 'ON_ITEM_LOADED',
  GALLERY_CHANGE: 'ON_GALLERY_CHANGE',
  ITEM_ACTION_TRIGGERED: 'ON_ITEM_ACTION_TRIGGERED',
  CURRENT_ITEM_CHANGED: 'ON_CURRENT_ITEM_CHANGED',
  ITEM_CLICKED: 'ON_ITEM_CLICKED', //for bi report only
  DOWNLOAD_BUTTON_CLICKED: 'ON_DOWNLOAD_BUTTON_CLICKED', //for Bi report only
  BUY_NOW_CLICKED: 'ON_BUY_NOW_CLICKED', //for Bi report only
  THUMBNAIL_CLICKED: 'ON_THUMBNAIL_CLICKED', //for Bi report only

  NEED_MORE_ITEMS: 'NEED_MORE_ITEMS',
};

export default EVENTS;
